// Generated by gencpp from file follow/Leg.msg
// DO NOT EDIT!


#ifndef FOLLOW_MESSAGE_LEG_H
#define FOLLOW_MESSAGE_LEG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace follow
{
template <class ContainerAllocator>
struct Leg_
{
  typedef Leg_<ContainerAllocator> Type;

  Leg_()
    : position()
    , confidence(0.0)  {
    }
  Leg_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef float _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::follow::Leg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::follow::Leg_<ContainerAllocator> const> ConstPtr;

}; // struct Leg_

typedef ::follow::Leg_<std::allocator<void> > Leg;

typedef boost::shared_ptr< ::follow::Leg > LegPtr;
typedef boost::shared_ptr< ::follow::Leg const> LegConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::follow::Leg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::follow::Leg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace follow

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'follow': ['/home/tbf/proj/follow/src/follow/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::follow::Leg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::follow::Leg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::follow::Leg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::follow::Leg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::follow::Leg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::follow::Leg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::follow::Leg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8000af3463f92157ee303c820e3b02c6";
  }

  static const char* value(const ::follow::Leg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8000af3463f92157ULL;
  static const uint64_t static_value2 = 0xee303c820e3b02c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::follow::Leg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "follow/Leg";
  }

  static const char* value(const ::follow::Leg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::follow::Leg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n\
float32 confidence\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::follow::Leg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::follow::Leg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Leg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::follow::Leg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::follow::Leg_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOLLOW_MESSAGE_LEG_H
