// Generated by gencpp from file follow/LegArray.msg
// DO NOT EDIT!


#ifndef FOLLOW_MESSAGE_LEGARRAY_H
#define FOLLOW_MESSAGE_LEGARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <follow/Leg.h>

namespace follow
{
template <class ContainerAllocator>
struct LegArray_
{
  typedef LegArray_<ContainerAllocator> Type;

  LegArray_()
    : header()
    , legs()  {
    }
  LegArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , legs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::follow::Leg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::follow::Leg_<ContainerAllocator> >::other >  _legs_type;
  _legs_type legs;





  typedef boost::shared_ptr< ::follow::LegArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::follow::LegArray_<ContainerAllocator> const> ConstPtr;

}; // struct LegArray_

typedef ::follow::LegArray_<std::allocator<void> > LegArray;

typedef boost::shared_ptr< ::follow::LegArray > LegArrayPtr;
typedef boost::shared_ptr< ::follow::LegArray const> LegArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::follow::LegArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::follow::LegArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace follow

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'follow': ['/home/tbf/proj/follow/src/follow/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::follow::LegArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::follow::LegArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::follow::LegArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::follow::LegArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::follow::LegArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::follow::LegArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::follow::LegArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e932f47090c69cbf30f535c2ab02e32";
  }

  static const char* value(const ::follow::LegArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e932f47090c69cbULL;
  static const uint64_t static_value2 = 0xf30f535c2ab02e32ULL;
};

template<class ContainerAllocator>
struct DataType< ::follow::LegArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "follow/LegArray";
  }

  static const char* value(const ::follow::LegArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::follow::LegArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
Leg[] legs\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: follow/Leg\n\
geometry_msgs/Point position\n\
float32 confidence\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::follow::LegArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::follow::LegArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.legs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LegArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::follow::LegArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::follow::LegArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "legs[]" << std::endl;
    for (size_t i = 0; i < v.legs.size(); ++i)
    {
      s << indent << "  legs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::follow::Leg_<ContainerAllocator> >::stream(s, indent + "    ", v.legs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOLLOW_MESSAGE_LEGARRAY_H
